// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	MastCompany            string
	MastDepartment         string
	MastUsers              string
	SecurityEvent          string
	SecurityGroupRelations string
	SecurityGroups         string
	SecurityModule         string
	SecurityRights         string
	SecurityScreen         string
}{
	MastCompany:            "mast_company",
	MastDepartment:         "mast_department",
	MastUsers:              "mast_users",
	SecurityEvent:          "security_event",
	SecurityGroupRelations: "security_group_relations",
	SecurityGroups:         "security_groups",
	SecurityModule:         "security_module",
	SecurityRights:         "security_rights",
	SecurityScreen:         "security_screen",
}
