// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SecurityGroupRelation is an object representing the database table.
type SecurityGroupRelation struct {
	GroupCode   string `boil:"group_code" json:"group_code" toml:"group_code" yaml:"group_code"`
	UserCode    string `boil:"user_code" json:"user_code" toml:"user_code" yaml:"user_code"`
	CompanyCode string `boil:"company_code" json:"company_code" toml:"company_code" yaml:"company_code"`
	ID          int64  `boil:"id" json:"id" toml:"id" yaml:"id"`

	R *securityGroupRelationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L securityGroupRelationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SecurityGroupRelationColumns = struct {
	GroupCode   string
	UserCode    string
	CompanyCode string
	ID          string
}{
	GroupCode:   "group_code",
	UserCode:    "user_code",
	CompanyCode: "company_code",
	ID:          "id",
}

var SecurityGroupRelationTableColumns = struct {
	GroupCode   string
	UserCode    string
	CompanyCode string
	ID          string
}{
	GroupCode:   "security_group_relations.group_code",
	UserCode:    "security_group_relations.user_code",
	CompanyCode: "security_group_relations.company_code",
	ID:          "security_group_relations.id",
}

// Generated where

var SecurityGroupRelationWhere = struct {
	GroupCode   whereHelperstring
	UserCode    whereHelperstring
	CompanyCode whereHelperstring
	ID          whereHelperint64
}{
	GroupCode:   whereHelperstring{field: "\"security_group_relations\".\"group_code\""},
	UserCode:    whereHelperstring{field: "\"security_group_relations\".\"user_code\""},
	CompanyCode: whereHelperstring{field: "\"security_group_relations\".\"company_code\""},
	ID:          whereHelperint64{field: "\"security_group_relations\".\"id\""},
}

// SecurityGroupRelationRels is where relationship names are stored.
var SecurityGroupRelationRels = struct {
}{}

// securityGroupRelationR is where relationships are stored.
type securityGroupRelationR struct {
}

// NewStruct creates a new relationship struct
func (*securityGroupRelationR) NewStruct() *securityGroupRelationR {
	return &securityGroupRelationR{}
}

// securityGroupRelationL is where Load methods for each relationship are stored.
type securityGroupRelationL struct{}

var (
	securityGroupRelationAllColumns            = []string{"group_code", "user_code", "company_code", "id"}
	securityGroupRelationColumnsWithoutDefault = []string{"group_code", "user_code", "company_code"}
	securityGroupRelationColumnsWithDefault    = []string{"id"}
	securityGroupRelationPrimaryKeyColumns     = []string{"group_code", "user_code", "company_code"}
)

type (
	// SecurityGroupRelationSlice is an alias for a slice of pointers to SecurityGroupRelation.
	// This should almost always be used instead of []SecurityGroupRelation.
	SecurityGroupRelationSlice []*SecurityGroupRelation
	// SecurityGroupRelationHook is the signature for custom SecurityGroupRelation hook methods
	SecurityGroupRelationHook func(context.Context, boil.ContextExecutor, *SecurityGroupRelation) error

	securityGroupRelationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	securityGroupRelationType                 = reflect.TypeOf(&SecurityGroupRelation{})
	securityGroupRelationMapping              = queries.MakeStructMapping(securityGroupRelationType)
	securityGroupRelationPrimaryKeyMapping, _ = queries.BindMapping(securityGroupRelationType, securityGroupRelationMapping, securityGroupRelationPrimaryKeyColumns)
	securityGroupRelationInsertCacheMut       sync.RWMutex
	securityGroupRelationInsertCache          = make(map[string]insertCache)
	securityGroupRelationUpdateCacheMut       sync.RWMutex
	securityGroupRelationUpdateCache          = make(map[string]updateCache)
	securityGroupRelationUpsertCacheMut       sync.RWMutex
	securityGroupRelationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var securityGroupRelationBeforeInsertHooks []SecurityGroupRelationHook
var securityGroupRelationBeforeUpdateHooks []SecurityGroupRelationHook
var securityGroupRelationBeforeDeleteHooks []SecurityGroupRelationHook
var securityGroupRelationBeforeUpsertHooks []SecurityGroupRelationHook

var securityGroupRelationAfterInsertHooks []SecurityGroupRelationHook
var securityGroupRelationAfterSelectHooks []SecurityGroupRelationHook
var securityGroupRelationAfterUpdateHooks []SecurityGroupRelationHook
var securityGroupRelationAfterDeleteHooks []SecurityGroupRelationHook
var securityGroupRelationAfterUpsertHooks []SecurityGroupRelationHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SecurityGroupRelation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SecurityGroupRelation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SecurityGroupRelation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SecurityGroupRelation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SecurityGroupRelation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SecurityGroupRelation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SecurityGroupRelation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SecurityGroupRelation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SecurityGroupRelation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range securityGroupRelationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSecurityGroupRelationHook registers your hook function for all future operations.
func AddSecurityGroupRelationHook(hookPoint boil.HookPoint, securityGroupRelationHook SecurityGroupRelationHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		securityGroupRelationBeforeInsertHooks = append(securityGroupRelationBeforeInsertHooks, securityGroupRelationHook)
	case boil.BeforeUpdateHook:
		securityGroupRelationBeforeUpdateHooks = append(securityGroupRelationBeforeUpdateHooks, securityGroupRelationHook)
	case boil.BeforeDeleteHook:
		securityGroupRelationBeforeDeleteHooks = append(securityGroupRelationBeforeDeleteHooks, securityGroupRelationHook)
	case boil.BeforeUpsertHook:
		securityGroupRelationBeforeUpsertHooks = append(securityGroupRelationBeforeUpsertHooks, securityGroupRelationHook)
	case boil.AfterInsertHook:
		securityGroupRelationAfterInsertHooks = append(securityGroupRelationAfterInsertHooks, securityGroupRelationHook)
	case boil.AfterSelectHook:
		securityGroupRelationAfterSelectHooks = append(securityGroupRelationAfterSelectHooks, securityGroupRelationHook)
	case boil.AfterUpdateHook:
		securityGroupRelationAfterUpdateHooks = append(securityGroupRelationAfterUpdateHooks, securityGroupRelationHook)
	case boil.AfterDeleteHook:
		securityGroupRelationAfterDeleteHooks = append(securityGroupRelationAfterDeleteHooks, securityGroupRelationHook)
	case boil.AfterUpsertHook:
		securityGroupRelationAfterUpsertHooks = append(securityGroupRelationAfterUpsertHooks, securityGroupRelationHook)
	}
}

// One returns a single securityGroupRelation record from the query.
func (q securityGroupRelationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SecurityGroupRelation, error) {
	o := &SecurityGroupRelation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for security_group_relations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SecurityGroupRelation records from the query.
func (q securityGroupRelationQuery) All(ctx context.Context, exec boil.ContextExecutor) (SecurityGroupRelationSlice, error) {
	var o []*SecurityGroupRelation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SecurityGroupRelation slice")
	}

	if len(securityGroupRelationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SecurityGroupRelation records in the query.
func (q securityGroupRelationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count security_group_relations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q securityGroupRelationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if security_group_relations exists")
	}

	return count > 0, nil
}

// SecurityGroupRelations retrieves all the records using an executor.
func SecurityGroupRelations(mods ...qm.QueryMod) securityGroupRelationQuery {
	mods = append(mods, qm.From("\"security_group_relations\""))
	return securityGroupRelationQuery{NewQuery(mods...)}
}

// FindSecurityGroupRelation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSecurityGroupRelation(ctx context.Context, exec boil.ContextExecutor, groupCode string, userCode string, companyCode string, selectCols ...string) (*SecurityGroupRelation, error) {
	securityGroupRelationObj := &SecurityGroupRelation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"security_group_relations\" where \"group_code\"=$1 AND \"user_code\"=$2 AND \"company_code\"=$3", sel,
	)

	q := queries.Raw(query, groupCode, userCode, companyCode)

	err := q.Bind(ctx, exec, securityGroupRelationObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from security_group_relations")
	}

	if err = securityGroupRelationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return securityGroupRelationObj, err
	}

	return securityGroupRelationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SecurityGroupRelation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no security_group_relations provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(securityGroupRelationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	securityGroupRelationInsertCacheMut.RLock()
	cache, cached := securityGroupRelationInsertCache[key]
	securityGroupRelationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			securityGroupRelationAllColumns,
			securityGroupRelationColumnsWithDefault,
			securityGroupRelationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(securityGroupRelationType, securityGroupRelationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(securityGroupRelationType, securityGroupRelationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"security_group_relations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"security_group_relations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into security_group_relations")
	}

	if !cached {
		securityGroupRelationInsertCacheMut.Lock()
		securityGroupRelationInsertCache[key] = cache
		securityGroupRelationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SecurityGroupRelation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SecurityGroupRelation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	securityGroupRelationUpdateCacheMut.RLock()
	cache, cached := securityGroupRelationUpdateCache[key]
	securityGroupRelationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			securityGroupRelationAllColumns,
			securityGroupRelationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update security_group_relations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"security_group_relations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, securityGroupRelationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(securityGroupRelationType, securityGroupRelationMapping, append(wl, securityGroupRelationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update security_group_relations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for security_group_relations")
	}

	if !cached {
		securityGroupRelationUpdateCacheMut.Lock()
		securityGroupRelationUpdateCache[key] = cache
		securityGroupRelationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q securityGroupRelationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for security_group_relations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for security_group_relations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SecurityGroupRelationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), securityGroupRelationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"security_group_relations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, securityGroupRelationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in securityGroupRelation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all securityGroupRelation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SecurityGroupRelation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no security_group_relations provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(securityGroupRelationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	securityGroupRelationUpsertCacheMut.RLock()
	cache, cached := securityGroupRelationUpsertCache[key]
	securityGroupRelationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			securityGroupRelationAllColumns,
			securityGroupRelationColumnsWithDefault,
			securityGroupRelationColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			securityGroupRelationAllColumns,
			securityGroupRelationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert security_group_relations, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(securityGroupRelationPrimaryKeyColumns))
			copy(conflict, securityGroupRelationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"security_group_relations\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(securityGroupRelationType, securityGroupRelationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(securityGroupRelationType, securityGroupRelationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert security_group_relations")
	}

	if !cached {
		securityGroupRelationUpsertCacheMut.Lock()
		securityGroupRelationUpsertCache[key] = cache
		securityGroupRelationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SecurityGroupRelation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SecurityGroupRelation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SecurityGroupRelation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), securityGroupRelationPrimaryKeyMapping)
	sql := "DELETE FROM \"security_group_relations\" WHERE \"group_code\"=$1 AND \"user_code\"=$2 AND \"company_code\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from security_group_relations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for security_group_relations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q securityGroupRelationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no securityGroupRelationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from security_group_relations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for security_group_relations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SecurityGroupRelationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(securityGroupRelationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), securityGroupRelationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"security_group_relations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, securityGroupRelationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from securityGroupRelation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for security_group_relations")
	}

	if len(securityGroupRelationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SecurityGroupRelation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSecurityGroupRelation(ctx, exec, o.GroupCode, o.UserCode, o.CompanyCode)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SecurityGroupRelationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SecurityGroupRelationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), securityGroupRelationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"security_group_relations\".* FROM \"security_group_relations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, securityGroupRelationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SecurityGroupRelationSlice")
	}

	*o = slice

	return nil
}

// SecurityGroupRelationExists checks if the SecurityGroupRelation row exists.
func SecurityGroupRelationExists(ctx context.Context, exec boil.ContextExecutor, groupCode string, userCode string, companyCode string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"security_group_relations\" where \"group_code\"=$1 AND \"user_code\"=$2 AND \"company_code\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, groupCode, userCode, companyCode)
	}
	row := exec.QueryRowContext(ctx, sql, groupCode, userCode, companyCode)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if security_group_relations exists")
	}

	return exists, nil
}
